from BaseClasses import Item, ItemClassification
import typing

from .Options import TrapAmount, CloverPitOptions

class ItemData(typing.NamedTuple):
    code: typing.Optional[int]
    classification: any
    amount: int = 1

class CloverItem(Item):
    game: str = "CloverPit"


CHARM_TABLE = {
    "Charm: Ankh": ItemData(123001, ItemClassification.progression),
    "Charm: Horseshoe": ItemData(123002, ItemClassification.progression),
    "Charm: Golden Horseshoe": ItemData(123003, ItemClassification.progression),
    "Charm: Hamsa": ItemData(123004, ItemClassification.progression),
    "Charm: Rotated Hamsa": ItemData(123005, ItemClassification.progression),
    "Charm: Lucky Cat": ItemData(123006, ItemClassification.progression),
    "Charm: Chonky Cat": ItemData(123007, ItemClassification.progression),
    "Charm: Swole Cat": ItemData(123008, ItemClassification.progression),
    "Charm: One Trick Pony": ItemData(123009, ItemClassification.progression),
    "Charm: Red Shiny Rock": ItemData(123010, ItemClassification.progression),
    "Charm: Tarot Deck": ItemData(123011, ItemClassification.progression),
    "Charm: Dung Beetle": ItemData(123012, ItemClassification.progression),
    "Charm: Grandma's Purse": ItemData(123013, ItemClassification.progression),
    "Charm: Pentacle": ItemData(123014, ItemClassification.progression),
    "Charm: Property Certificate": ItemData(123015, ItemClassification.progression),
    "Charm: Nuclear Button": ItemData(123016, ItemClassification.progression),
    "Charm: Dear Diary": ItemData(123017, ItemClassification.progression),
    "Charm: Megaphone": ItemData(123018, ItemClassification.progression),
    "Charm: Super Capacitor": ItemData(123019, ItemClassification.progression),
    "Charm: Dynamo": ItemData(123020, ItemClassification.progression),
    "Charm: Scratch And Hope": ItemData(123021, ItemClassification.progression),
    "Charm: Stonks": ItemData(123022, ItemClassification.progression),
    "Charm: Car Battery": ItemData(123023, ItemClassification.progression),
    "Charm: Expired Meds": ItemData(123024, ItemClassification.progression),
    "Charm: Midas Touch": ItemData(123025, ItemClassification.progression),
    "Charm: Number 1": ItemData(123026, ItemClassification.progression),
    "Charm: Number 2": ItemData(123027, ItemClassification.progression),
    "Charm: Pain Killers": ItemData(123028, ItemClassification.progression),
    "Charm: Lost Wallet": ItemData(123029, ItemClassification.progression),
    "Charm: Calendar": ItemData(123030, ItemClassification.progression),
    "Charm: Little Star": ItemData(123031, ItemClassification.progression),
    "Charm: Cigarettes": ItemData(123032, ItemClassification.progression),
    "Charm: Fidelity Card": ItemData(123033, ItemClassification.progression),
    "Charm: Sardines": ItemData(123034, ItemClassification.progression),
    "Charm: Broken Calculator": ItemData(123035, ItemClassification.progression),
    "Charm: The Collector": ItemData(123036, ItemClassification.progression),
    "Charm: Channeler of Fortune": ItemData(123037, ItemClassification.progression),
    "Charm: Nose": ItemData(123038, ItemClassification.progression),
    "Charm: Eye Jar": ItemData(123039, ItemClassification.progression),
    "Charm: VoiceMail": ItemData(123040, ItemClassification.progression),
    "Charm: Ring Bell": ItemData(123041, ItemClassification.progression),
    "Charm: Consolation Prize": ItemData(123042, ItemClassification.progression),
    "Charm: Dark Lotus": ItemData(123043, ItemClassification.progression),
    "Charm: Weird Clock": ItemData(123044, ItemClassification.progression),
    "Charm: Music Tape": ItemData(123045, ItemClassification.progression),
    "Charm: Shopping Cart": ItemData(123046, ItemClassification.progression),
    "Charm: Crowbar": ItemData(123047, ItemClassification.progression),
    "Charm: Disc A": ItemData(123048, ItemClassification.progression),
    "Charm: Disc B": ItemData(123049, ItemClassification.progression),
    "Charm: Disc C": ItemData(123050, ItemClassification.progression),
    "Charm: Cardboard House": ItemData(123051, ItemClassification.progression),
    "Charm: Lost Briefcase": ItemData(123052, ItemClassification.progression),
    "Charm: Electricity Meter": ItemData(123053, ItemClassification.progression),
    "Charm: Potato Battery": ItemData(123054, ItemClassification.progression),
    "Charm: Ancient Coin": ItemData(123055, ItemClassification.progression),
    "Charm: Cat Food": ItemData(123056, ItemClassification.progression),
    "Charm: Depression": ItemData(123057, ItemClassification.progression),
    "Charm: Toy Train": ItemData(123058, ItemClassification.progression),
    "Charm: Steam Locomotive": ItemData(123059, ItemClassification.progression),
    "Charm: Diesel Locomotive": ItemData(123060, ItemClassification.progression),
    "Charm: Clover Voucher": ItemData(123061, ItemClassification.progression),
    "Charm: CloverPot": ItemData(123062, ItemClassification.progression),
    "Charm: CloverPet": ItemData(123063, ItemClassification.progression),
    "Charm: CloverField": ItemData(123064, ItemClassification.progression),
    "Charm: Mushrooms": ItemData(123065, ItemClassification.progression),
    "Charm: Vine's Soup": ItemData(123066, ItemClassification.progression),
    "Charm: Very Big Mushroom": ItemData(123067, ItemClassification.progression),
    "Charm: Abyssu": ItemData(123068, ItemClassification.progression),
    "Charm: Vorago": ItemData(123069, ItemClassification.progression),
    "Charm: Barathrum": ItemData(123070, ItemClassification.progression),
    "Charm: Stain": ItemData(123071, ItemClassification.progression),
    "Charm: Abstract Painting": ItemData(123072, ItemClassification.progression),
    "Charm: Pareidolia": ItemData(123073, ItemClassification.progression),
    "Charm: Hourglass": ItemData(123074, ItemClassification.progression),
    "Charm: Fruit Basket": ItemData(123075, ItemClassification.progression),
    "Charm: 7 Sins Stone": ItemData(123076, ItemClassification.progression),
    "Charm: Necklace": ItemData(123077, ItemClassification.progression),
    "Charm: CloverBell": ItemData(123078, ItemClassification.progression),
    "Charm: Red Pepper": ItemData(123079, ItemClassification.progression),
    "Charm: Green Pepper": ItemData(123080, ItemClassification.progression),
    "Charm: Rotten Pepper": ItemData(123081, ItemClassification.progression),
    "Charm: Bell Pepper": ItemData(123082, ItemClassification.progression),
    "Charm: Golden Pepper": ItemData(123083, ItemClassification.progression),
    "Charm: Demon's Horn": ItemData(123084, ItemClassification.progression),
    "Charm: Necronomicon": ItemData(123085, ItemClassification.progression),
    "Charm: Holy Bible": ItemData(123086, ItemClassification.progression),
    "Charm: Baphomet": ItemData(123087, ItemClassification.progression),
    "Charm: Cross": ItemData(123088, ItemClassification.progression),
    "Charm: Rosary": ItemData(123089, ItemClassification.progression),
    "Charm: Book Of Shadows": ItemData(123090, ItemClassification.progression),
    "Charm: Gabihbb'h": ItemData(123091, ItemClassification.progression),
    "Charm: Possessed Cell Phone": ItemData(123092, ItemClassification.progression),
    "Charm: Magical Tomato": ItemData(123093, ItemClassification.progression),
    "Charm: Ritual Bell": ItemData(123094, ItemClassification.progression),
    "Charm: Crystal Skull": ItemData(123095, ItemClassification.progression),
    "Charm: Evil Deal": ItemData(123096, ItemClassification.progression),
    "Charm: Chastity Belt": ItemData(123097, ItemClassification.progression),
    "Charm: Photo Book": ItemData(123098, ItemClassification.progression),
    "Charm: Lemon Picture": ItemData(123099, ItemClassification.progression),
    "Charm: Cherry Picture": ItemData(123100, ItemClassification.progression),
    "Charm: Clover Picture": ItemData(123101, ItemClassification.progression),
    "Charm: Bell Picture": ItemData(123102, ItemClassification.progression),
    "Charm: Diamond Picture": ItemData(123103, ItemClassification.progression),
    "Charm: Treasure Picture": ItemData(123104, ItemClassification.progression),
    "Charm: Seven Picture": ItemData(123105, ItemClassification.progression),
    "Charm: Clicker": ItemData(123106, ItemClassification.progression),
    "Charm: AA Batteries": ItemData(123107, ItemClassification.progression),
    "Charm: Crystal Sphere": ItemData(123108, ItemClassification.progression),
    "Charm: Naughty Dealer": ItemData(123109, ItemClassification.progression),
    "Charm: Greedy King": ItemData(123110, ItemClassification.progression),
    "Charm: Raging Capitalist": ItemData(123111, ItemClassification.progression),
    "Charm: Personal Trainer": ItemData(123112, ItemClassification.progression),
    "Charm: Electrician": ItemData(123113, ItemClassification.progression),
    "Charm: Fortune Teller": ItemData(123114, ItemClassification.progression),
    "Charm: Golden Lemon": ItemData(123115, ItemClassification.progression),
    "Charm: Golden Cherry": ItemData(123116, ItemClassification.progression),
    "Charm: Golden Clover": ItemData(123117, ItemClassification.progression),
    "Charm: Golden Bell": ItemData(123118, ItemClassification.progression),
    "Charm: Golden Diamond": ItemData(123119, ItemClassification.progression),
    "Charm: Golden Treasure": ItemData(123120, ItemClassification.progression),
    "Charm: Golden Seven": ItemData(123121, ItemClassification.progression),
    "Charm: Bricks": ItemData(123122, ItemClassification.progression),
    "Charm: Wood": ItemData(123123, ItemClassification.progression),
    "Charm: Sheep": ItemData(123124, ItemClassification.progression),
    "Charm: Wheat": ItemData(123125, ItemClassification.progression),
    "Charm: Stone": ItemData(123126, ItemClassification.progression),
    "Charm: Harbor": ItemData(123127, ItemClassification.progression),
    "Charm: Thief": ItemData(123128, ItemClassification.progression),
    "Charm: Wheelbarrow": ItemData(123129, ItemClassification.progression),
    "Charm: Shoe": ItemData(123130, ItemClassification.progression),
    "Charm: Thimble": ItemData(123131, ItemClassification.progression),
    "Charm: Iron": ItemData(123132, ItemClassification.progression),
    "Charm: Car": ItemData(123133, ItemClassification.progression),
    "Charm: Ship": ItemData(123134, ItemClassification.progression),
    "Charm: Tuba Hat": ItemData(123135, ItemClassification.progression),
    "Charm: Ace Of Hearts": ItemData(123136, ItemClassification.progression),
    "Charm: Ace Of Clubs": ItemData(123137, ItemClassification.progression),
    "Charm: Ace Of Diamonds": ItemData(123138, ItemClassification.progression),
    "Charm: Ace Of Spades": ItemData(123139, ItemClassification.progression),
    "Charm: Jimbo": ItemData(123140, ItemClassification.progression),
    "Charm: D4": ItemData(123141, ItemClassification.progression),
    "Charm: D6": ItemData(123142, ItemClassification.progression),
    "Charm: D20": ItemData(123143, ItemClassification.progression),
}

CALL_TABLE = {
    "Call: Please don't throw my stuff away!": ItemData(124000, ItemClassification.progression),
    "Call: I can't quit now!": ItemData(124002, ItemClassification.progression),
    "Call: Can I borrow some green?": ItemData(124003, ItemClassification.progression),
    "Call: Can I eat something?": ItemData(124004, ItemClassification.progression),

    "Call: This time I'm betting on Green!": ItemData(124005, ItemClassification.progression),
    "Call: This time I'm betting on Yellow!": ItemData(124006, ItemClassification.progression),
    "Call: This time I'm betting on Orange!": ItemData(124007, ItemClassification.progression),
    "Call: If I keep trying, the patterns will align!": ItemData(124008, ItemClassification.progression),
    "Call: It's kinda fun!": ItemData(124009, ItemClassification.progression),
    "Call: I'm sure the value will rise!": ItemData(124010, ItemClassification.progression),

    "Call: Can I get some Energy Drinks?": ItemData(124011, ItemClassification.progression),

    "Call: Life gave me lemons": ItemData(124012, ItemClassification.progression),
    "Call: I used to eat healthy...": ItemData(124013, ItemClassification.progression),
    "Call: Today's my lucky day!": ItemData(124014, ItemClassification.progression),
    "Call: I need to be there!": ItemData(124015, ItemClassification.progression),
    "Call: Please, I'll give you anything": ItemData(124016, ItemClassification.progression),
    "Call: I need money!": ItemData(124017, ItemClassification.progression),
    "Call: I didn't hurt anybody...": ItemData(124018, ItemClassification.progression),

    "Call: I need supplements!": ItemData(124019, ItemClassification.progression),
    "Call: I'm feeling lucky!": ItemData(124020, ItemClassification.progression),
    "Call: Gold and Diamonds are a good investment!": ItemData(124021, ItemClassification.progression),
    "Call: I'm gonna go All In!": ItemData(124022, ItemClassification.progression),

    "Call: I'm thinking of some strategies!": ItemData(124023, ItemClassification.progression),
    "Call: I found a winning strategy!": ItemData(124024, ItemClassification.progression),

    "Call: I like cryptic values!": ItemData(124026, ItemClassification.progression),
    "Call: I love shiny stuff!": ItemData(124028, ItemClassification.progression),
    "Call: I don't care about the price!": ItemData(124029, ItemClassification.progression),
    "Call: My head hurts!": ItemData(124030, ItemClassification.progression),
    "Call: Give me back my money!": ItemData(124031, ItemClassification.progression),

    "Call: There's nothing to eat but mould.": ItemData(124032, ItemClassification.progression),
    "Call: Wait, what day is it?": ItemData(124033, ItemClassification.progression),
    "Call: I've already bet it all!": ItemData(124034, ItemClassification.progression),

    "Call: I'm re-organizing my mind!": ItemData(124035, ItemClassification.progression),
    "Call: I see the patterns in my behaviour.": ItemData(124036, ItemClassification.progression),
    "Call: I'm feeling more energetic recently.": ItemData(124037, ItemClassification.progression),
    "Call: I need to heal myself.": ItemData(124038, ItemClassification.progression),
    "Call: I'm being constant!": ItemData(124039, ItemClassification.progression),
    "Call: Help!": ItemData(124040, ItemClassification.progression),

    "Call: I want to address some stuff.": ItemData(124041, ItemClassification.progression),
    "Call: I'll take back control of my life.": ItemData(124042, ItemClassification.progression),

    "Card Pack 1": ItemData(124100, ItemClassification.progression),
    "Card Pack 2": ItemData(124101, ItemClassification.progression),
    "Card Pack 3": ItemData(124102, ItemClassification.progression),
    "Card Pack 4": ItemData(124103, ItemClassification.progression),
    "Card Pack 5": ItemData(124104, ItemClassification.progression),
    "Card Pack 6": ItemData(124105, ItemClassification.progression),
    "Card Pack 7": ItemData(124106, ItemClassification.progression),
}

PROGRESSIVE_TABLE = {
    "Progressive Skeleton": ItemData(123801, ItemClassification.progression),
    "Progressive Drawer": ItemData(123802, ItemClassification.progression),
    "Progressive Luck": ItemData(123803, ItemClassification.progression),
}

STUPID_TABLE = {
    "Win": ItemData(123999, ItemClassification.filler)
}

FILLER_TABLE = {
    "5x Clover Tickets": ItemData(125000, ItemClassification.filler),
    "Bonus Deadline Tickets": ItemData(125001, ItemClassification.filler),
    "Bonus Starting Tickets": ItemData(125002, ItemClassification.filler)
}

TRAP_TABLE = {
    "Clover Trap": ItemData(123600, ItemClassification.trap),
    "Coin Trap": ItemData(123700, ItemClassification.trap)
}
item_table = {
    **CHARM_TABLE,
    **PROGRESSIVE_TABLE,
    **CALL_TABLE,
    **STUPID_TABLE,
    **FILLER_TABLE,
    **TRAP_TABLE
}