Tracker:AddLocations("locations/Buy.json")
Tracker:AddLocations("locations/Normal Call.json")
Tracker:AddLocations("locations/Red Button.json")
Tracker:AddLocations("locations/Red Call.json")
Tracker:AddLocations("locations/Sacred Call.json")
Tracker:AddLocations("locations/Trigger.json")
