Tracker:AddLocations("locations/Buy.json")
Tracker:AddLocations("locations/Deadline.json")
Tracker:AddLocations("locations/Key.json")
Tracker:AddLocations("locations/Memory Card.json")
Tracker:AddLocations("locations/Normal Call.json")
Tracker:AddLocations("locations/Red Button.json")
Tracker:AddLocations("locations/Red Call.json")
Tracker:AddLocations("locations/Sacred Call.json")
Tracker:AddLocations("locations/Score.json")
Tracker:AddLocations("locations/Skeleton.json")
Tracker:AddLocations("locations/Toilet.json")
Tracker:AddLocations("locations/Trigger.json")
Tracker:AddLocations("locations/Overworld.json")
